name: hadolint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  hadolint:
    name: hadolint
    uses: book000/templates/.github/workflows/reusable-hadolint-ci.yml@a8b7f3c4f10d3da67893d91f84f8a019bf79ed4d # master
